// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfBrzzK_9zG1JtVtPhv2swA6EQ5KS2Tv4',
    appId: '1:965618798802:web:bc3e8d884d49d7be729d0b',
    messagingSenderId: '965618798802',
    projectId: 'finalexam-52451',
    authDomain: 'finalexam-52451.firebaseapp.com',
    storageBucket: 'finalexam-52451.appspot.com',
    measurementId: 'G-TXBZY3SPY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSa98xUtL-SfymxjvOQDo1BJ7TQ6uexo',
    appId: '1:965618798802:android:a5c1bd4140bdfe94729d0b',
    messagingSenderId: '965618798802',
    projectId: 'finalexam-52451',
    storageBucket: 'finalexam-52451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-sVgwLFMb3SQZ2pwMeGzl8fbyHlXizuI',
    appId: '1:965618798802:ios:61185e45324a0602729d0b',
    messagingSenderId: '965618798802',
    projectId: 'finalexam-52451',
    storageBucket: 'finalexam-52451.appspot.com',
    iosBundleId: 'com.example.finalexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-sVgwLFMb3SQZ2pwMeGzl8fbyHlXizuI',
    appId: '1:965618798802:ios:15431a3092100c7a729d0b',
    messagingSenderId: '965618798802',
    projectId: 'finalexam-52451',
    storageBucket: 'finalexam-52451.appspot.com',
    iosBundleId: 'com.example.finalexam.RunnerTests',
  );
}
